version: '3.8'

services:
  todo_service:
    build:
      context: ./todo_app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - todo_data:/app/data

  shorturl_service:
    build:
      context: ./shorturl_app
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - shorturl_data:/app/data

volumes:
  todo_data:
  shorturl_data:
